route:
  group_by: [Alertname]
  receiver: email-me

receivers:
- name: email-me
  email_configs:
  - to: seuemail@gmail.com
    from: seuemailg@gmail.com
    smarthost: smtp.gmail.com:587
    auth_username: seusuario
    auth_identity: seusuario@gmail.com
    auth_password: senhadoemail
