global:
 scrape_interval: 5s
 external_labels:
   monitor: 'Prometheus Monitoramento'
rule_files:
 - 'alert.rules'
scrape_configs:
 - job_name: 'prometheus'
   static_configs:
     - targets: ['127.0.0.1:9090']

 - job_name: 'node-exporter'
   static_configs:
     - targets: ['192.168.1.22:9100'] ## COLOQUE O IP DO PROPRIO SERVIDOR PROMETHEUS

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - alertmanager:9093
